'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'en' | 'es' | 'zh' | 'fr'

export interface LanguageOption {
  code: Language
  name: string
  flag: string
  locale: string
}

export const languages: LanguageOption[] = [
  { code: 'en', name: 'English', flag: '🇬🇧', locale: 'en-GB' },
  { code: 'es', name: 'Español', flag: '🇪🇸', locale: 'es-ES' },
  { code: 'zh', name: '中文', flag: '🇨🇳', locale: 'zh-CN' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', locale: 'fr-FR' },
]

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  getTranslation: (key: string) => string
  getDestinationName: (destinationSlug: string, fallbackName: string) => string
  getCategoryName: (categorySlug: string, fallbackName: string) => string
  getPricingTierName: (tierName: string) => string
  getCountryName: (countryName: string) => string
  getLanguageName: (languageName: string) => string
  languageOptions: LanguageOption[]
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// UI translations for common elements
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.activities': 'Activities',
    'nav.destinations': 'Destinations',
    'nav.blog': 'Blog',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.wishlist': 'Wishlist',
    'nav.cart': 'Cart',
    'nav.bookings': 'My Bookings',
    
    // Footer sections
    'footer.company': 'Company',
    'footer.support': 'Support', 
    'footer.vendors': 'For Vendors',
    
    // Company pages
    'page.about_us': 'About Us',
    'page.careers': 'Careers',
    'page.press': 'Press',
    'page.blog': 'Blog',
    
    // Support pages
    'page.help_center': 'Help Center',
    'page.contact_us': 'Contact Us',
    'page.cancellation_policy': 'Cancellation Policy',
    'page.privacy_policy': 'Privacy Policy',
    
    // Vendor pages
    'page.list_experience': 'List Your Experience',
    'page.vendor_login': 'Vendor Login',
    'page.vendor_dashboard': 'Vendor Dashboard',
    'page.affiliate_program': 'Affiliate Program',
    
    // Footer additional
    'footer.connect': 'Connect',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter_desc': 'Get travel tips and inspiration delivered to your inbox.',
    'footer.subscribe': 'Subscribe',
    'footer.your_email': 'Your email',
    'footer.copyright': '© 2024 FindTravelMate. All rights reserved.',
    'page.terms': 'Terms of Service',
    'page.cookies': 'Cookie Policy',

    // Common buttons
    'button.book': 'Book Now',
    'button.add_to_cart': 'Add to Cart',
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    'button.search': 'Search',
    'button.filter': 'Filter',
    'button.sort': 'Sort',
    'button.view_more': 'View More',
    'button.view_less': 'View Less',

    // Blog
    'blog.title': 'Travel Blog',
    'blog.subtitle': 'Inspiration, tips, and stories from around the world',
    'blog.all_posts': 'All Posts',
    'blog.read_more': 'Read More',
    'blog.homepage.title': 'Travel Stories & Tips',
    'blog.homepage.subtitle': 'Inspiration and advice from our travel experts',
    'blog.homepage.read_blog': 'Read Our Blog',
    'blog.newsletter.title': 'Subscribe to Our Newsletter',
    'blog.newsletter.subtitle': 'Get travel tips, destination guides, and exclusive deals delivered to your inbox',
    'blog.newsletter.placeholder': 'Enter your email',
    'blog.newsletter.subscribe': 'Subscribe',
    'blog.category.destination_guides': 'Destination Guides',
    'blog.category.travel_tips': 'Travel Tips',
    'blog.category.travel_planning': 'Travel Planning',
    'blog.category.sustainable_travel': 'Sustainable Travel',
    'blog.category.food_culture': 'Food & Culture',

    // Activity details
    'activity.highlights': 'Highlights',
    'activity.included': 'What\'s Included',
    'activity.excluded': 'What\'s Not Included',
    'activity.meeting_point': 'Meeting Point',
    'activity.faqs': 'Frequently Asked Questions',
    'activity.reviews': 'Reviews',
    'activity.similar': 'Similar Activities',
    'activity.what_to_expect': 'What to Expect',
    'activity.pricing': 'Pricing Options',
    'activity.schedule': 'Available Times',
    'activity.add_ons': 'Add-ons',

    // Filters
    'filter.price': 'Price',
    'filter.duration': 'Duration',
    'filter.rating': 'Rating',
    'filter.category': 'Category',
    'filter.language': 'Language',

    // Messages
    'message.no_translation': 'This content is not available in the selected language',
    'message.loading': 'Loading...',
    'message.not_available_in': 'not available in',
    'message.not_translated': 'This content has not been translated yet. Please switch to English to view this information.',
    'message.error': 'An error occurred',
    'message.success': 'Success!',
    'message.empty_cart': 'Your cart is empty',
    'message.empty_wishlist': 'Your wishlist is empty',

    // Homepage
    'homepage.hero.title': 'Meet Your Perfect Travel Partner',
    'homepage.hero.subtitle': 'Connect with local experts and discover authentic experiences',
    'homepage.search.placeholder': 'Where would you like to explore?',
    'homepage.trust.millions.title': 'Trusted by millions',
    'homepage.trust.millions.desc': 'Over 150,000 activities worldwide',
    'homepage.trust.cancellation.title': 'Free cancellation',
    'homepage.trust.cancellation.desc': 'Most activities offer free cancellation',
    'homepage.trust.guarantee.title': 'Best price guarantee',
    'homepage.trust.guarantee.desc': "Find it cheaper? We'll refund the difference",
    'homepage.destinations.title': 'Popular destinations',
    'homepage.destinations.subtitle': 'Discover the world\'s most amazing places',
    'homepage.activities.title': 'Top-rated activities',
    'homepage.activities.subtitle': 'Handpicked experiences our travelers love',
    'homepage.categories.title': 'Explore by category',
    'homepage.categories.subtitle': 'Find activities that match your interests',
    
    // Vendor CTA Section
    'homepage.vendor.title': 'Become a vendor',
    'homepage.vendor.subtitle': 'Join thousands of activity providers and reach millions of travelers worldwide',
    'homepage.vendor.list_activity': 'List your activity',
    'homepage.vendor.login': 'Vendor login',

    // Search page
    'search.title.all_activities': 'All Activities',
    'search.title.search_results': 'Search results for',
    'search.activities_found': 'activities found',
    'search.placeholder': 'Search for activities...',
    'search.sort.recommended': 'Recommended',
    'search.sort.price_low_high': 'Price: Low to High',
    'search.sort.price_high_low': 'Price: High to Low',
    'search.sort.highest_rated': 'Highest Rated',
    'search.sort.duration': 'Duration',
    'search.load_more': 'Load More',
    'search.loading': 'Loading...',
    'search.no_results.title': 'No activities found',
    'search.no_results.subtitle': 'Try adjusting your filters or search terms',
    'search.clear_filters': 'Clear Filters',

    // Filter sidebar
    'filter.title': 'Filters',
    'filter.clear_all': 'Clear all',
    'filter.all_categories': 'All categories',
    'filter.all_destinations': 'All destinations',
    'filter.price_range': 'Price Range (€)',
    'filter.price.min': 'Min',
    'filter.price.max': 'Max',
    'filter.duration_hours': 'Duration (hours)',
    'filter.min_rating': 'Minimum Rating',
    'filter.any_rating': 'Any rating',
    'filter.features': 'Features',
    'filter.free_cancellation': 'Free cancellation',
    'filter.instant_confirmation': 'Instant confirmation',
    'filter.skip_the_line': 'Skip the line',
    'filter.bestseller': 'Bestseller',

    // Activity badges
    'badge.bestseller': 'BESTSELLER',
    'badge.skip_the_line': 'Skip the line',
    'badge.free_cancellation': 'Free cancellation',
    'badge.instant_confirmation': 'Instant confirmation',

    // Activity detail sections
    'activity.overview': 'Overview',
    'activity.important_info': 'Important information',
    'activity.what_to_bring': 'What to bring',
    'activity.not_suitable_for': 'Not suitable for',
    'activity.dress_code': 'Dress code',
    'activity.covid_measures': 'COVID-19 safety measures',
    'activity.provider': 'Activity provider',
    'activity.verified': 'Verified',
    'activity.meeting_point_photos': 'Meeting point photos',
    'activity.map_not_available': 'Map not available',
    'activity.booked': 'booked',

    // Booking widget
    'booking.select_date': 'Select date',
    'booking.select_time': 'Select time',
    'booking.select_tickets': 'Select tickets',
    'booking.adult': 'Adult',
    'booking.child': 'Child',
    'booking.total': 'Total',
    'booking.from': 'From',
    'booking.per_person': 'per person',
    'booking.popular_choice': 'POPULAR CHOICE',
    'booking.people_viewing': 'people',
    'booking.viewing_now': 'viewing this activity now',
    'booking.only_spots_left': 'Only',
    'booking.spots_left': 'spots left',
    'booking.for_selected_date': 'for selected date!',
    'booking.duration': 'Duration',
    'booking.max_group_size': 'Max group size',
    'booking.max_people': 'Max',
    'booking.people': 'people',
    'booking.add_to_cart': 'Add to Cart',
    'booking.adding': 'Adding...',
    'booking.free_cancellation': 'Free cancellation up to',
    'booking.hours_before': 'hours before',
    'booking.instant_confirmation': 'Instant confirmation',
    'booking.was': 'was',
    
    // Time slots
    'timeslots.select_time': 'Select Time',
    'timeslots.sold_out': 'Sold Out',
    
    // Add-ons
    'addons.add_ons': 'Add-ons & Extras',
    'addons.optional': 'Optional',
    'addons.extra': 'Extra',
    'addons.required': 'Required',
    'addons.optional_extras': 'Optional Extras',
    'addons.total': 'Total',
    
    // Pricing tiers
    'pricing.select_option': 'Select Option',
    
    // Reviews
    'reviews.customer_reviews': 'Customer Reviews',
    'reviews.write_review': 'Write a Review',
    'reviews.helpful': 'Helpful',
    'reviews.show_more': 'Show More',
    'reviews.show_less': 'Show Less',
    
    // Destinations
    'destination.tokyo': 'Tokyo',
    'destination.paris': 'Paris',
    'destination.london': 'London',
    'destination.new-york': 'New York',
    'destination.rome': 'Rome',
    'destination.barcelona': 'Barcelona',
    'destination.berlin': 'Berlin',
    'destination.amsterdam': 'Amsterdam',
    'destination.prague': 'Prague',
    
    // Activity Features
    'features.title': 'Activity Features',
    'features.verified_activity': 'Verified Activity',
    'features.best_price_guarantee': 'Best Price Guarantee',
    'features.mobile_ticket': 'Mobile Ticket',
    'features.likely_to_sell_out': 'Likely to Sell Out',
    'features.response_time': 'Response Time',
    'features.wheelchair_accessible': 'Wheelchair Accessible',
    'features.stroller_accessible': 'Stroller Accessible',
    'features.service_animals_allowed': 'Service Animals Allowed',
    'features.infant_seats_available': 'Infant Seats Available',
    'features.gift_option_available': 'Gift Option Available',
    'features.reserve_now_pay_later': 'Reserve Now, Pay Later',
    'features.covid_measures': 'COVID-19 Safety Measures',
    'features.weather_dependent': 'Weather Dependent',
    'features.video_preview_available': 'Video Preview Available',
    
    // Categories
    'category.food-drink': 'Food & Drink',
    'category.tours-sightseeing': 'Tours & Sightseeing',
    'category.outdoor-adventures': 'Outdoor Adventures',
    'category.arts-culture': 'Arts & Culture',
    'category.nightlife-entertainment': 'Nightlife & Entertainment',
    'category.workshops-classes': 'Workshops & Classes',
    'category.family-friendly': 'Family Friendly',
    'category.romantic': 'Romantic',
    'category.wellness-spa': 'Wellness & Spa',
    'category.sports-fitness': 'Sports & Fitness',
    'category.museums-attractions': 'Museums & Attractions',
    
    // Pricing Tiers
    'pricing.standard': 'Standard',
    'pricing.premium': 'Premium',
    'pricing.vip': 'VIP',
    'pricing.pedestal_access': 'Pedestal Access',
    'pricing.crown_access': 'Crown Access',
    'pricing.mezzanine': 'Mezzanine',
    'pricing.orchestra': 'Orchestra',
    'pricing.vip_package': 'VIP Package',
    'pricing.at_the_top': 'At the Top',
    'pricing.at_the_top_sky': 'At the Top SKY',
    
    // Countries
    'country.france': 'France',
    'country.united_kingdom': 'United Kingdom',
    'country.italy': 'Italy',
    'country.spain': 'Spain',
    'country.netherlands': 'Netherlands',
    'country.united_states': 'United States',
    'country.japan': 'Japan',
    'country.united_arab_emirates': 'United Arab Emirates',
    'country.czech_republic': 'Czech Republic',
    'country.turkey': 'Turkey',
    
    // Language names
    'language.english': 'English',
    'language.french': 'French',
    'language.spanish': 'Spanish',
    'language.italian': 'Italian',
    'language.german': 'German',
    'language.portuguese': 'Portuguese',
    'language.chinese': 'Chinese',
    'language.japanese': 'Japanese',
    
    // About page
    'about.title': 'About Us',
    'about.hero_subtitle': 'Connecting travelers with unforgettable experiences worldwide',
    'about.mission_title': 'Our Mission',
    'about.mission_p1': 'At FindTravelMate, we believe that travel is more than just visiting new places—it\'s about creating meaningful connections, discovering authentic experiences, and making memories that last a lifetime.',
    'about.mission_p2': 'We partner with local experts and activity providers worldwide to bring you the best tours, activities, and experiences. Whether you\'re seeking adventure, culture, relaxation, or something completely unique, we\'re here to help you find your perfect travel partner.',
    'about.value_community': 'Community',
    'about.value_community_desc': 'Building connections between travelers and local experts',
    'about.value_global': 'Global Reach',
    'about.value_global_desc': '150,000+ activities in destinations worldwide',
    'about.value_quality': 'Quality',
    'about.value_quality_desc': 'Verified vendors and authentic experiences only',
    'about.value_passion': 'Passion',
    'about.value_passion_desc': 'Driven by love for travel and discovery',
    'about.story_title': 'Our Story',
    'about.story_p1': 'Founded in 2020, FindTravelMate was born from a simple idea: every traveler deserves to connect with authentic local experiences. Our founders, passionate travelers themselves, saw the gap between tourists and the incredible people who truly know their destinations.',
    'about.story_p2': 'Today, we\'ve grown into a global platform connecting millions of travelers with thousands of verified vendors across hundreds of destinations. But our mission remains the same—to make every journey extraordinary.',
    'about.stat_activities': 'Activities',
    'about.stat_destinations': 'Destinations',
    'about.stat_travelers': 'Happy Travelers',
    'about.stat_vendors': 'Verified Vendors',
    'about.cta_title': 'Ready to Start Your Journey?',
    'about.cta_subtitle': 'Explore thousands of amazing experiences waiting for you',
    'about.cta_button': 'Explore Activities',

    // Careers page
    'careers.title': 'Join Our Team',
    'careers.hero_subtitle': 'Help us connect millions of travelers with unforgettable experiences',
    'careers.why_work_title': 'Why Work With Us',
    'careers.passion_travel': 'Passion for Travel',
    'careers.passion_travel_desc': 'Work with people who love travel as much as you do',
    'careers.collaborative_culture': 'Collaborative Culture',
    'careers.collaborative_culture_desc': 'Join a diverse, inclusive team that values every voice',
    'careers.growth_opportunities': 'Growth Opportunities',
    'careers.growth_opportunities_desc': 'Continuous learning and career development',
    'careers.benefits_title': 'Benefits & Perks',
    'careers.benefit_salary': 'Competitive salary and equity packages',
    'careers.benefit_insurance': 'Comprehensive health, dental, and vision insurance',
    'careers.benefit_flexible': 'Flexible working hours and remote options',
    'careers.benefit_pto': 'Unlimited PTO policy',
    'careers.benefit_travel': 'Annual travel stipend for experiences',
    'careers.benefit_development': 'Professional development budget',
    'careers.benefit_401k': '401(k) matching',
    'careers.benefit_parental': 'Parental leave',
    'careers.open_positions': 'Open Positions',
    'careers.no_openings': 'No open positions at the moment. Check back soon!',
    'careers.apply_now': 'Apply Now',
    'careers.cta_title': 'Don\'t See the Right Role?',
    'careers.cta_subtitle': 'We\'re always looking for talented people. Send us your resume!',
    'careers.get_in_touch': 'Get in Touch',
    'careers.job_engineering': 'Engineering',
    'careers.job_product': 'Product',
    'careers.job_customer_success': 'Customer Success',
    'careers.job_marketing': 'Marketing',
    'careers.job_remote': 'Remote',
    'careers.job_fulltime': 'Full-time',
    'careers.job_senior_fullstack': 'Senior Full Stack Engineer',
    'careers.job_product_manager': 'Product Manager',
    'careers.job_customer_success_manager': 'Customer Success Manager',
    'careers.job_marketing_manager': 'Marketing Manager',

    // User Account Pages
    // Profile/My Account page
    'account.my_account': 'My Account',
    'account.profile': 'Profile',
    'account.my_bookings': 'My Bookings',
    'account.wishlist': 'Wishlist',
    'account.settings': 'Settings',
    'account.profile_information': 'Profile Information',
    'account.edit_profile': 'Edit Profile',
    'account.full_name': 'Full Name',
    'account.phone_number': 'Phone Number',
    'account.email_address': 'Email Address',
    'account.verified': 'Verified',
    'account.not_verified': 'Not verified',
    'account.not_set': 'Not set',
    'account.member_since': 'Member Since',
    'account.save_changes': 'Save Changes',
    'account.cancel': 'Cancel',
    'account.loading': 'Loading...',
    'account.total_bookings': 'Total Bookings',
    'account.wishlist_items': 'Wishlist Items',
    'account.reviews': 'Reviews',

    // My Bookings page
    'bookings.title': 'My Bookings',
    'bookings.booking_confirmed': 'Booking Confirmed!',
    'bookings.confirmation_email_sent': 'Your booking has been confirmed. A confirmation email has been sent to your email address.',
    'bookings.book_more_activities': 'Book More Activities',
    'bookings.return_to_homepage': 'Return to Homepage',
    'bookings.confirmation_success': 'Your booking has been confirmed! Check your email for confirmation details.',
    'bookings.no_bookings_yet': 'No bookings yet',
    'bookings.start_exploring': 'Start exploring and book your next adventure',
    'bookings.browse_activities': 'Browse Activities',
    'bookings.booking_reference': 'Booking Reference',
    'bookings.status_confirmed': 'Confirmed',
    'bookings.status_pending': 'Pending',
    'bookings.status_cancelled': 'Cancelled',
    'bookings.status_completed': 'Completed',
    'bookings.adult': 'adult',
    'bookings.adults': 'adults',
    'bookings.child': 'child',
    'bookings.children': 'children',
    'bookings.duration': 'Duration',
    'bookings.special_requirements': 'Special Requirements',
    'bookings.view_details': 'View Details',
    'bookings.cancel_booking': 'Cancel Booking',
    'bookings.leave_review': 'Leave a Review',
    'bookings.loading_bookings': 'Loading your bookings...',

    // Wishlist page
    'wishlist.title': 'My Wishlist',
    'wishlist.activity': 'activity',
    'wishlist.activities': 'activities',
    'wishlist.saved': 'saved',
    'wishlist.empty_title': 'Your wishlist is empty',
    'wishlist.empty_description': 'Start adding activities you\'re interested in by clicking the heart icon',
    'wishlist.explore_activities': 'Explore Activities',
    'wishlist.loading': 'Loading your wishlist...',
    'wishlist.try_again': 'Try Again',
    'wishlist.failed_to_load': 'Failed to load wishlist. Please try again.',

    // Vendor Dashboard
    'vendor.dashboard': 'Vendor Dashboard',
    'vendor.welcome_back': 'Welcome back',
    'vendor.add_activity': 'Add Activity',
    'vendor.total_activities': 'Total Activities',
    'vendor.active_activities': 'Active Activities',
    'vendor.total_bookings': 'Total Bookings',
    'vendor.total_revenue': 'Total Revenue',
    'vendor.your_activities': 'Your Activities',
    'vendor.no_activities_yet': 'No Activities Yet',
    'vendor.get_started_message': 'Get started by creating your first activity. Share your experiences with travelers worldwide!',
    'vendor.create_first_activity': 'Create Your First Activity',
    'vendor.activity': 'Activity',
    'vendor.category': 'Category',
    'vendor.price': 'Price',
    'vendor.rating': 'Rating',
    'vendor.status': 'Status',
    'vendor.actions': 'Actions',
    'vendor.active': 'Active',
    'vendor.inactive': 'Inactive',
    'vendor.view': 'View',
    'vendor.edit': 'Edit',
    'vendor.delete': 'Delete',
    'vendor.activate': 'Activate',
    'vendor.deactivate': 'Deactivate',
    'vendor.recent_bookings': 'Recent Bookings',
    'vendor.list': 'List',
    'vendor.calendar': 'Calendar',
    'vendor.no_bookings_yet': 'No bookings yet.',
    'vendor.booking_ref': 'Booking Ref',
    'vendor.customer': 'Customer',
    'vendor.date': 'Date',
    'vendor.amount': 'Amount',
    'vendor.approve': 'Approve',
    'vendor.reject': 'Reject',
    'vendor.check_in': 'Check In',
    'vendor.cancel': 'Cancel',
    'vendor.loading': 'Loading...',
    'vendor.confirm_delete': 'Are you sure you want to delete this activity?',
    'vendor.delete_failed': 'Failed to delete activity',
    'vendor.toggle_failed': 'Failed to toggle activity status',
    'vendor.approve_confirm': 'Approve this booking?',
    'vendor.approve_failed': 'Failed to approve booking',
    'vendor.reject_reason': 'Please provide a reason for rejection:',
    'vendor.reject_failed': 'Failed to reject booking',
    'vendor.cancel_reason': 'Please provide a reason for cancellation:',
    'vendor.cancel_failed': 'Failed to cancel booking',
    'vendor.checkin_confirm': 'Mark this booking as checked in?',
    'vendor.checkin_failed': 'Failed to check in booking',

    // Vendor Login
    'vendor.login_title': 'Vendor Login',
    'vendor.login_subtitle': 'Sign in to manage your activities',
    'vendor.email_address': 'Email Address',
    'vendor.password': 'Password',
    'vendor.signing_in': 'Signing in...',
    'vendor.sign_in': 'Sign In',
    'vendor.no_account': 'Don\'t have a vendor account?',
    'vendor.register_here': 'Register here',
    'vendor.back_to_home': 'Back to Home',
    'vendor.access_denied': 'Access denied. Vendor account required.',
    'vendor.verify_failed': 'Failed to verify vendor account. Please try again.',
    'vendor.invalid_credentials': 'Invalid email or password',

    // Cart page
    'cart.empty': 'Your cart is empty',
    'cart.browse_activities': 'Browse Activities',
    'cart.title': 'Shopping Cart',
    'cart.order_summary': 'Order Summary',
    'cart.proceed_to_checkout': 'Proceed to Checkout',
    'cart.continue_shopping': 'Continue Shopping',
    'cart.secure_checkout': 'Secure Checkout',

    // Checkout page
    'checkout.back_to_cart': 'Back to Cart',
    'checkout.title': 'Checkout',
    'checkout.first_name': 'First Name *',
    'checkout.last_name': 'Last Name *',
    'checkout.email': 'Email Address *',
    'checkout.phone': 'Phone Number *',
    'checkout.payment_method': 'Payment Method',
    'checkout.order_summary': 'Order Summary',
    'checkout.validate_name': 'Please enter your full name',
    'checkout.validate_email': 'Please enter your email address',
    'checkout.validate_phone': 'Please enter your phone number',
    'checkout.validate_terms': 'Please agree to the terms and conditions',
    'checkout.booking_success': 'Booking completed successfully!',
    'checkout.booking_error': 'Failed to complete booking. Please try again.',

    // Header dashboard links
    'nav.admin_dashboard': 'Admin Dashboard',
    'nav.vendor_dashboard': 'Vendor Dashboard',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.activities': 'Actividades',
    'nav.destinations': 'Destinos',
    'nav.blog': 'Blog',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.signin': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.profile': 'Perfil',
    'nav.wishlist': 'Lista de Deseos',
    'nav.cart': 'Carrito',
    'nav.bookings': 'Mis Reservas',
    
    // Footer sections
    'footer.company': 'Empresa',
    'footer.support': 'Soporte', 
    'footer.vendors': 'Para Proveedores',
    
    // Company pages
    'page.about_us': 'Quiénes Somos',
    'page.careers': 'Carreras',
    'page.press': 'Prensa',
    'page.blog': 'Blog',
    
    // Support pages
    'page.help_center': 'Centro de Ayuda',
    'page.contact_us': 'Contáctanos',
    'page.cancellation_policy': 'Política de Cancelación',
    'page.privacy_policy': 'Política de Privacidad',
    
    // Vendor pages
    'page.list_experience': 'Lista Tu Experiencia',
    'page.vendor_login': 'Acceso Proveedor',
    'page.vendor_dashboard': 'Panel de Proveedor',
    'page.affiliate_program': 'Programa de Afiliados',
    
    // Footer additional
    'footer.connect': 'Conectar',
    'footer.newsletter': 'Boletín',
    'footer.newsletter_desc': 'Recibe consejos de viaje e inspiración en tu bandeja de entrada.',
    'footer.subscribe': 'Suscribirse',
    'footer.your_email': 'Tu email',
    'footer.copyright': '© 2024 FindTravelMate. Todos los derechos reservados.',
    'page.terms': 'Términos de Servicio',
    'page.cookies': 'Política de Cookies',

    // Common buttons
    'button.book': 'Reservar Ahora',
    'button.add_to_cart': 'Añadir al Carrito',
    'button.save': 'Guardar',
    'button.cancel': 'Cancelar',
    'button.search': 'Buscar',
    'button.filter': 'Filtrar',
    'button.sort': 'Ordenar',
    'button.view_more': 'Ver Más',
    'button.view_less': 'Ver Menos',

    // Blog
    'blog.title': 'Blog de Viajes',
    'blog.subtitle': 'Inspiración, consejos e historias de todo el mundo',
    'blog.all_posts': 'Todas las Publicaciones',
    'blog.read_more': 'Leer Más',
    'blog.homepage.title': 'Historias y Consejos de Viaje',
    'blog.homepage.subtitle': 'Inspiración y consejos de nuestros expertos en viajes',
    'blog.homepage.read_blog': 'Leer Nuestro Blog',
    'blog.newsletter.title': 'Suscríbete a Nuestro Boletín',
    'blog.newsletter.subtitle': 'Recibe consejos de viaje, guías de destinos y ofertas exclusivas en tu bandeja de entrada',
    'blog.newsletter.placeholder': 'Ingresa tu email',
    'blog.newsletter.subscribe': 'Suscribirse',
    'blog.category.destination_guides': 'Guías de Destinos',
    'blog.category.travel_tips': 'Consejos de Viaje',
    'blog.category.travel_planning': 'Planificación de Viajes',
    'blog.category.sustainable_travel': 'Viaje Sostenible',
    'blog.category.food_culture': 'Comida y Cultura',

    // Activity details
    'activity.highlights': 'Aspectos Destacados',
    'activity.included': 'Qué Está Incluido',
    'activity.excluded': 'Qué No Está Incluido',
    'activity.meeting_point': 'Punto de Encuentro',
    'activity.faqs': 'Preguntas Frecuentes',
    'activity.reviews': 'Reseñas',
    'activity.similar': 'Actividades Similares',
    'activity.what_to_expect': 'Qué Esperar',
    'activity.pricing': 'Opciones de Precio',
    'activity.schedule': 'Horarios Disponibles',
    'activity.add_ons': 'Complementos',

    // Filters
    'filter.price': 'Precio',
    'filter.duration': 'Duración',
    'filter.rating': 'Calificación',
    'filter.category': 'Categoría',
    'filter.language': 'Idioma',

    // Messages
    'message.no_translation': 'Este contenido no está disponible en el idioma seleccionado',
    'message.loading': 'Cargando...',
    'message.not_available_in': 'no disponible en',
    'message.not_translated': 'Este contenido aún no ha sido traducido. Cambie a inglés para ver esta información.',
    'message.error': 'Ocurrió un error',
    'message.success': '¡Éxito!',
    'message.empty_cart': 'Tu carrito está vacío',
    'message.empty_wishlist': 'Tu lista de deseos está vacía',

    // Homepage
    'homepage.hero.title': 'Encuentra Tu Compañero de Viaje Perfecto',
    'homepage.hero.subtitle': 'Conecta con expertos locales y descubre experiencias auténticas',
    'homepage.search.placeholder': '¿Dónde te gustaría explorar?',
    'homepage.trust.millions.title': 'Confianza de millones',
    'homepage.trust.millions.desc': 'Más de 150,000 actividades en todo el mundo',
    'homepage.trust.cancellation.title': 'Cancelación gratuita',
    'homepage.trust.cancellation.desc': 'La mayoría de actividades ofrecen cancelación gratuita',
    'homepage.trust.guarantee.title': 'Garantía del mejor precio',
    'homepage.trust.guarantee.desc': '¿Lo encontraste más barato? Te reembolsamos la diferencia',
    'homepage.destinations.title': 'Destinos populares',
    'homepage.destinations.subtitle': 'Descubre los lugares más increíbles del mundo',
    'homepage.activities.title': 'Actividades mejor valoradas',
    'homepage.activities.subtitle': 'Experiencias seleccionadas que nuestros viajeros adoran',
    'homepage.categories.title': 'Explorar por categoría',
    'homepage.categories.subtitle': 'Encuentra actividades que coincidan con tus intereses',
    
    // Vendor CTA Section
    'homepage.vendor.title': 'Conviértete en proveedor',
    'homepage.vendor.subtitle': 'Únete a miles de proveedores de actividades y alcanza millones de viajeros en todo el mundo',
    'homepage.vendor.list_activity': 'Lista tu actividad',
    'homepage.vendor.login': 'Acceso de proveedor',

    // Search page
    'search.title.all_activities': 'Todas las Actividades',
    'search.title.search_results': 'Resultados de búsqueda para',
    'search.activities_found': 'actividades encontradas',
    'search.placeholder': 'Buscar actividades...',
    'search.sort.recommended': 'Recomendado',
    'search.sort.price_low_high': 'Precio: Menor a Mayor',
    'search.sort.price_high_low': 'Precio: Mayor a Menor',
    'search.sort.highest_rated': 'Mejor Valorado',
    'search.sort.duration': 'Duración',
    'search.load_more': 'Cargar Más',
    'search.loading': 'Cargando...',
    'search.no_results.title': 'No se encontraron actividades',
    'search.no_results.subtitle': 'Intenta ajustar tus filtros o términos de búsqueda',
    'search.clear_filters': 'Limpiar Filtros',

    // Filter sidebar
    'filter.title': 'Filtros',
    'filter.clear_all': 'Limpiar todo',
    'filter.all_categories': 'Todas las categorías',
    'filter.all_destinations': 'Todos los destinos',
    'filter.price_range': 'Rango de Precio (€)',
    'filter.price.min': 'Mín',
    'filter.price.max': 'Máx',
    'filter.duration_hours': 'Duración (horas)',
    'filter.min_rating': 'Calificación Mínima',
    'filter.any_rating': 'Cualquier calificación',
    'filter.features': 'Características',
    'filter.free_cancellation': 'Cancelación gratuita',
    'filter.instant_confirmation': 'Confirmación instantánea',
    'filter.skip_the_line': 'Saltar la cola',
    'filter.bestseller': 'Más vendido',

    // Activity badges
    'badge.bestseller': 'MÁS VENDIDO',
    'badge.skip_the_line': 'Saltar la cola',
    'badge.free_cancellation': 'Cancelación gratuita',
    'badge.instant_confirmation': 'Confirmación instantánea',

    // Activity detail sections
    'activity.overview': 'Descripción',
    'activity.important_info': 'Información importante',
    'activity.what_to_bring': 'Qué traer',
    'activity.not_suitable_for': 'No adecuado para',
    'activity.dress_code': 'Código de vestimenta',
    'activity.covid_measures': 'Medidas de seguridad COVID-19',
    'activity.provider': 'Proveedor de la actividad',
    'activity.verified': 'Verificado',
    'activity.meeting_point_photos': 'Fotos del punto de encuentro',
    'activity.map_not_available': 'Mapa no disponible',
    'activity.booked': 'reservado',

    // Booking widget
    'booking.select_date': 'Seleccionar fecha',
    'booking.select_time': 'Seleccionar hora',
    'booking.select_tickets': 'Seleccionar entradas',
    'booking.adult': 'Adulto',
    'booking.child': 'Niño',
    'booking.total': 'Total',
    'booking.from': 'Desde',
    'booking.per_person': 'por persona',
    'booking.popular_choice': 'OPCIÓN POPULAR',
    'booking.people_viewing': 'personas',
    'booking.viewing_now': 'viendo esta actividad ahora',
    'booking.only_spots_left': 'Solo',
    'booking.spots_left': 'plazas disponibles',
    'booking.for_selected_date': 'para la fecha seleccionada!',
    'booking.duration': 'Duración',
    'booking.max_group_size': 'Tamaño máximo de grupo',
    'booking.max_people': 'Máx',
    'booking.people': 'personas',
    'booking.add_to_cart': 'Añadir al Carrito',
    'booking.adding': 'Añadiendo...',
    'booking.free_cancellation': 'Cancelación gratuita hasta',
    'booking.hours_before': 'horas antes',
    'booking.instant_confirmation': 'Confirmación instantánea',
    'booking.was': 'era',
    
    // Time slots
    'timeslots.select_time': 'Seleccionar Hora',
    'timeslots.sold_out': 'Agotado',
    
    // Add-ons
    'addons.add_ons': 'Extras y Complementos',
    'addons.optional': 'Opcional',
    'addons.extra': 'Extra',
    'addons.required': 'Requerido',
    'addons.optional_extras': 'Extras Opcionales',
    'addons.total': 'Total',
    
    // Pricing tiers
    'pricing.select_option': 'Seleccionar Opción',
    
    // Reviews
    'reviews.customer_reviews': 'Opiniones de Clientes',
    'reviews.write_review': 'Escribir una Reseña',
    'reviews.helpful': 'Útil',
    'reviews.show_more': 'Ver Más',
    'reviews.show_less': 'Ver Menos',
    
    // Destinations
    'destination.tokyo': 'Tokio',
    'destination.paris': 'París',
    'destination.london': 'Londres',
    'destination.new-york': 'Nueva York',
    'destination.rome': 'Roma',
    'destination.barcelona': 'Barcelona',
    'destination.berlin': 'Berlín',
    'destination.amsterdam': 'Ámsterdam',
    'destination.prague': 'Praga',
    
    // Activity Features
    'features.title': 'Características de la Actividad',
    'features.verified_activity': 'Actividad Verificada',
    'features.best_price_guarantee': 'Garantía del Mejor Precio',
    'features.mobile_ticket': 'Boleto Móvil',
    'features.likely_to_sell_out': 'Probable Agotamiento',
    'features.response_time': 'Tiempo de Respuesta',
    'features.wheelchair_accessible': 'Accesible en Silla de Ruedas',
    'features.stroller_accessible': 'Accesible con Cochecito',
    'features.service_animals_allowed': 'Animales de Servicio Permitidos',
    'features.infant_seats_available': 'Asientos para Bebés Disponibles',
    'features.gift_option_available': 'Opción de Regalo Disponible',
    'features.reserve_now_pay_later': 'Reservar Ahora, Pagar Después',
    'features.covid_measures': 'Medidas de Seguridad COVID-19',
    'features.weather_dependent': 'Dependiente del Clima',
    'features.video_preview_available': 'Vista Previa en Video Disponible',
    
    // Categories
    'category.food-drink': 'Comida y Bebida',
    'category.tours-sightseeing': 'Tours y Turismo',
    'category.outdoor-adventures': 'Aventuras al Aire Libre',
    'category.arts-culture': 'Arte y Cultura',
    'category.nightlife-entertainment': 'Vida Nocturna y Entretenimiento',
    'category.workshops-classes': 'Talleres y Clases',
    'category.family-friendly': 'Familiar',
    'category.romantic': 'Romántico',
    'category.wellness-spa': 'Bienestar y Spa',
    'category.sports-fitness': 'Deportes y Fitness',
    'category.museums-attractions': 'Museos y Atracciones',
    
    // Pricing Tiers
    'pricing.standard': 'Estándar',
    'pricing.premium': 'Premium',
    'pricing.vip': 'VIP',
    'pricing.pedestal_access': 'Acceso Pedestal',
    'pricing.crown_access': 'Acceso Corona',
    'pricing.mezzanine': 'Entresuelo',
    'pricing.orchestra': 'Orquesta',
    'pricing.vip_package': 'Paquete VIP',
    'pricing.at_the_top': 'En la Cima',
    'pricing.at_the_top_sky': 'En la Cima Cielo',
    
    // Countries
    'country.france': 'Francia',
    'country.united_kingdom': 'Reino Unido',
    'country.italy': 'Italia',
    'country.spain': 'España',
    'country.netherlands': 'Países Bajos',
    'country.united_states': 'Estados Unidos',
    'country.japan': 'Japón',
    'country.united_arab_emirates': 'Emiratos Árabes Unidos',
    'country.czech_republic': 'República Checa',
    'country.turkey': 'Turquía',
    
    // Language names
    'language.english': 'Inglés',
    'language.french': 'Francés',
    'language.spanish': 'Español',
    'language.italian': 'Italiano',
    'language.german': 'Alemán',
    'language.portuguese': 'Portugués',
    'language.chinese': 'Chino',
    'language.japanese': 'Japonés',
    
    // About page
    'about.title': 'Quiénes Somos',
    'about.hero_subtitle': 'Conectando viajeros con experiencias inolvidables en todo el mundo',
    'about.mission_title': 'Nuestra Misión',
    'about.mission_p1': 'En FindTravelMate, creemos que viajar es más que solo visitar lugares nuevos—se trata de crear conexiones significativas, descubrir experiencias auténticas y crear recuerdos que duren toda la vida.',
    'about.mission_p2': 'Nos asociamos con expertos locales y proveedores de actividades en todo el mundo para ofrecerte los mejores tours, actividades y experiencias. Ya sea que busques aventura, cultura, relajación o algo completamente único, estamos aquí para ayudarte a encontrar tu compañero de viaje perfecto.',
    'about.value_community': 'Comunidad',
    'about.value_community_desc': 'Construyendo conexiones entre viajeros y expertos locales',
    'about.value_global': 'Alcance Global',
    'about.value_global_desc': 'Más de 150,000 actividades en destinos de todo el mundo',
    'about.value_quality': 'Calidad',
    'about.value_quality_desc': 'Solo proveedores verificados y experiencias auténticas',
    'about.value_passion': 'Pasión',
    'about.value_passion_desc': 'Impulsados por el amor al viaje y el descubrimiento',
    'about.story_title': 'Nuestra Historia',
    'about.story_p1': 'Fundada en 2020, FindTravelMate nació de una idea simple: todo viajero merece conectarse con experiencias locales auténticas. Nuestros fundadores, viajeros apasionados ellos mismos, vieron la brecha entre los turistas y las personas increíbles que realmente conocen sus destinos.',
    'about.story_p2': 'Hoy, hemos crecido hasta convertirnos en una plataforma global que conecta millones de viajeros con miles de proveedores verificados en cientos de destinos. Pero nuestra misión sigue siendo la misma: hacer que cada viaje sea extraordinario.',
    'about.stat_activities': 'Actividades',
    'about.stat_destinations': 'Destinos',
    'about.stat_travelers': 'Viajeros Felices',
    'about.stat_vendors': 'Proveedores Verificados',
    'about.cta_title': '¿Listo para Comenzar tu Viaje?',
    'about.cta_subtitle': 'Explora miles de experiencias increíbles que te esperan',
    'about.cta_button': 'Explorar Actividades',

    // Careers page
    'careers.title': 'Únete a Nuestro Equipo',
    'careers.hero_subtitle': 'Ayúdanos a conectar millones de viajeros con experiencias inolvidables',
    'careers.why_work_title': '¿Por Qué Trabajar Con Nosotros?',
    'careers.passion_travel': 'Pasión por los Viajes',
    'careers.passion_travel_desc': 'Trabaja con personas que aman viajar tanto como tú',
    'careers.collaborative_culture': 'Cultura Colaborativa',
    'careers.collaborative_culture_desc': 'Únete a un equipo diverso e inclusivo que valora cada voz',
    'careers.growth_opportunities': 'Oportunidades de Crecimiento',
    'careers.growth_opportunities_desc': 'Aprendizaje continuo y desarrollo profesional',
    'careers.benefits_title': 'Beneficios y Ventajas',
    'careers.benefit_salary': 'Salario competitivo y paquetes de equity',
    'careers.benefit_insurance': 'Seguro médico, dental y de visión integral',
    'careers.benefit_flexible': 'Horarios flexibles y opciones remotas',
    'careers.benefit_pto': 'Política de vacaciones ilimitadas',
    'careers.benefit_travel': 'Subsidio anual de viajes para experiencias',
    'careers.benefit_development': 'Presupuesto para desarrollo profesional',
    'careers.benefit_401k': 'Contribución equivalente al 401(k)',
    'careers.benefit_parental': 'Licencia parental',
    'careers.open_positions': 'Puestos Abiertos',
    'careers.no_openings': 'No hay puestos abiertos en este momento. ¡Vuelve pronto!',
    'careers.apply_now': 'Aplicar Ahora',
    'careers.cta_title': '¿No Ves el Puesto Correcto?',
    'careers.cta_subtitle': 'Siempre estamos buscando personas talentosas. ¡Envíanos tu currículum!',
    'careers.get_in_touch': 'Ponte en Contacto',
    'careers.job_engineering': 'Ingeniería',
    'careers.job_product': 'Producto',
    'careers.job_customer_success': 'Éxito del Cliente',
    'careers.job_marketing': 'Marketing',
    'careers.job_remote': 'Remoto',
    'careers.job_fulltime': 'Tiempo completo',
    'careers.job_senior_fullstack': 'Ingeniero Full Stack Senior',
    'careers.job_product_manager': 'Gerente de Producto',
    'careers.job_customer_success_manager': 'Gerente de Éxito del Cliente',
    'careers.job_marketing_manager': 'Gerente de Marketing',

    // User Account Pages
    // Profile/My Account page
    'account.my_account': 'Mi Cuenta',
    'account.profile': 'Perfil',
    'account.my_bookings': 'Mis Reservas',
    'account.wishlist': 'Lista de Deseos',
    'account.settings': 'Configuración',
    'account.profile_information': 'Información del Perfil',
    'account.edit_profile': 'Editar Perfil',
    'account.full_name': 'Nombre Completo',
    'account.phone_number': 'Número de Teléfono',
    'account.email_address': 'Dirección de Email',
    'account.verified': 'Verificado',
    'account.not_verified': 'No verificado',
    'account.not_set': 'No establecido',
    'account.member_since': 'Miembro Desde',
    'account.save_changes': 'Guardar Cambios',
    'account.cancel': 'Cancelar',
    'account.loading': 'Cargando...',
    'account.total_bookings': 'Reservas Totales',
    'account.wishlist_items': 'Elementos en Lista de Deseos',
    'account.reviews': 'Reseñas',

    // My Bookings page
    'bookings.title': 'Mis Reservas',
    'bookings.booking_confirmed': '¡Reserva Confirmada!',
    'bookings.confirmation_email_sent': 'Tu reserva ha sido confirmada. Se ha enviado un email de confirmación a tu dirección de correo.',
    'bookings.book_more_activities': 'Reservar Más Actividades',
    'bookings.return_to_homepage': 'Volver al Inicio',
    'bookings.confirmation_success': '¡Tu reserva ha sido confirmada! Revisa tu email para los detalles de confirmación.',
    'bookings.no_bookings_yet': 'Aún no hay reservas',
    'bookings.start_exploring': 'Comienza a explorar y reserva tu próxima aventura',
    'bookings.browse_activities': 'Explorar Actividades',
    'bookings.booking_reference': 'Referencia de Reserva',
    'bookings.status_confirmed': 'Confirmado',
    'bookings.status_pending': 'Pendiente',
    'bookings.status_cancelled': 'Cancelado',
    'bookings.status_completed': 'Completado',
    'bookings.adult': 'adulto',
    'bookings.adults': 'adultos',
    'bookings.child': 'niño',
    'bookings.children': 'niños',
    'bookings.duration': 'Duración',
    'bookings.special_requirements': 'Requisitos Especiales',
    'bookings.view_details': 'Ver Detalles',
    'bookings.cancel_booking': 'Cancelar Reserva',
    'bookings.leave_review': 'Dejar una Reseña',
    'bookings.loading_bookings': 'Cargando tus reservas...',

    // Wishlist page
    'wishlist.title': 'Mi Lista de Deseos',
    'wishlist.activity': 'actividad',
    'wishlist.activities': 'actividades',
    'wishlist.saved': 'guardadas',
    'wishlist.empty_title': 'Tu lista de deseos está vacía',
    'wishlist.empty_description': 'Comienza a añadir actividades que te interesen haciendo clic en el icono del corazón',
    'wishlist.explore_activities': 'Explorar Actividades',
    'wishlist.loading': 'Cargando tu lista de deseos...',
    'wishlist.try_again': 'Intentar de Nuevo',
    'wishlist.failed_to_load': 'Error al cargar la lista de deseos. Por favor, inténtalo de nuevo.',

    // Vendor Dashboard
    'vendor.dashboard': 'Panel de Proveedor',
    'vendor.welcome_back': 'Bienvenido de vuelta',
    'vendor.add_activity': 'Añadir Actividad',
    'vendor.total_activities': 'Actividades Totales',
    'vendor.active_activities': 'Actividades Activas',
    'vendor.total_bookings': 'Reservas Totales',
    'vendor.total_revenue': 'Ingresos Totales',
    'vendor.your_activities': 'Tus Actividades',
    'vendor.no_activities_yet': 'Aún No Hay Actividades',
    'vendor.get_started_message': 'Comienza creando tu primera actividad. ¡Comparte tus experiencias con viajeros de todo el mundo!',
    'vendor.create_first_activity': 'Crear Tu Primera Actividad',
    'vendor.activity': 'Actividad',
    'vendor.category': 'Categoría',
    'vendor.price': 'Precio',
    'vendor.rating': 'Calificación',
    'vendor.status': 'Estado',
    'vendor.actions': 'Acciones',
    'vendor.active': 'Activa',
    'vendor.inactive': 'Inactiva',
    'vendor.view': 'Ver',
    'vendor.edit': 'Editar',
    'vendor.delete': 'Eliminar',
    'vendor.activate': 'Activar',
    'vendor.deactivate': 'Desactivar',
    'vendor.recent_bookings': 'Reservas Recientes',
    'vendor.list': 'Lista',
    'vendor.calendar': 'Calendario',
    'vendor.no_bookings_yet': 'Aún no hay reservas.',
    'vendor.booking_ref': 'Ref. Reserva',
    'vendor.customer': 'Cliente',
    'vendor.date': 'Fecha',
    'vendor.amount': 'Cantidad',
    'vendor.approve': 'Aprobar',
    'vendor.reject': 'Rechazar',
    'vendor.check_in': 'Registrar Entrada',
    'vendor.cancel': 'Cancelar',
    'vendor.loading': 'Cargando...',
    'vendor.confirm_delete': '¿Estás seguro de que quieres eliminar esta actividad?',
    'vendor.delete_failed': 'Error al eliminar actividad',
    'vendor.toggle_failed': 'Error al cambiar el estado de la actividad',
    'vendor.approve_confirm': '¿Aprobar esta reserva?',
    'vendor.approve_failed': 'Error al aprobar reserva',
    'vendor.reject_reason': 'Por favor proporciona una razón para el rechazo:',
    'vendor.reject_failed': 'Error al rechazar reserva',
    'vendor.cancel_reason': 'Por favor proporciona una razón para la cancelación:',
    'vendor.cancel_failed': 'Error al cancelar reserva',
    'vendor.checkin_confirm': '¿Marcar esta reserva como registrada?',
    'vendor.checkin_failed': 'Error al registrar entrada de reserva',

    // Vendor Login
    'vendor.login_title': 'Acceso de Proveedor',
    'vendor.login_subtitle': 'Inicia sesión para gestionar tus actividades',
    'vendor.email_address': 'Dirección de Email',
    'vendor.password': 'Contraseña',
    'vendor.signing_in': 'Iniciando sesión...',
    'vendor.sign_in': 'Iniciar Sesión',
    'vendor.no_account': '¿No tienes una cuenta de proveedor?',
    'vendor.register_here': 'Regístrate aquí',
    'vendor.back_to_home': 'Volver al Inicio',
    'vendor.access_denied': 'Acceso denegado. Se requiere cuenta de proveedor.',
    'vendor.verify_failed': 'Error al verificar cuenta de proveedor. Por favor, inténtalo de nuevo.',
    'vendor.invalid_credentials': 'Email o contraseña inválidos',

    // Cart page
    'cart.empty': 'Tu carrito está vacío',
    'cart.browse_activities': 'Explorar Actividades',
    'cart.title': 'Carrito de Compras',
    'cart.order_summary': 'Resumen del Pedido',
    'cart.proceed_to_checkout': 'Proceder al Pago',
    'cart.continue_shopping': 'Seguir Comprando',
    'cart.secure_checkout': 'Pago Seguro',

    // Checkout page
    'checkout.back_to_cart': 'Volver al Carrito',
    'checkout.title': 'Pago',
    'checkout.first_name': 'Nombre *',
    'checkout.last_name': 'Apellido *',
    'checkout.email': 'Correo Electrónico *',
    'checkout.phone': 'Número de Teléfono *',
    'checkout.payment_method': 'Método de Pago',
    'checkout.order_summary': 'Resumen del Pedido',
    'checkout.validate_name': 'Por favor ingrese su nombre completo',
    'checkout.validate_email': 'Por favor ingrese su correo electrónico',
    'checkout.validate_phone': 'Por favor ingrese su número de teléfono',
    'checkout.validate_terms': 'Por favor acepte los términos y condiciones',
    'checkout.booking_success': '¡Reserva completada con éxito!',
    'checkout.booking_error': 'Error al completar la reserva. Por favor intente de nuevo.',

    // Header dashboard links
    'nav.admin_dashboard': 'Panel de Administración',
    'nav.vendor_dashboard': 'Panel de Proveedor',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.activities': '活动',
    'nav.destinations': '目的地',
    'nav.blog': '博客',
    'nav.about': '关于',
    'nav.contact': '联系',
    'nav.signin': '登录',
    'nav.signup': '注册',
    'nav.logout': '登出',
    'nav.profile': '个人资料',
    'nav.wishlist': '愿望清单',
    'nav.cart': '购物车',
    'nav.bookings': '我的预订',
    
    // Footer sections
    'footer.company': '公司',
    'footer.support': '客户支持', 
    'footer.vendors': '供应商专区',
    
    // Company pages
    'page.about_us': '关于我们',
    'page.careers': '招聘',
    'page.press': '媒体中心',
    'page.blog': '博客',
    
    // Support pages
    'page.help_center': '帮助中心',
    'page.contact_us': '联系我们',
    'page.cancellation_policy': '取消政策',
    'page.privacy_policy': '隐私政策',
    
    // Vendor pages
    'page.list_experience': '发布体验',
    'page.vendor_login': '供应商登录',
    'page.vendor_dashboard': '供应商面板',
    'page.affiliate_program': '合作伙伴计划',
    
    // Footer additional
    'footer.connect': '关注我们',
    'footer.newsletter': '订阅简报',
    'footer.newsletter_desc': '获取旅行贴士和灵感，直送您的邮箱。',
    'footer.subscribe': '订阅',
    'footer.your_email': '您的邮箱',
    'footer.copyright': '© 2024 FindTravelMate. 版权所有。',
    'page.terms': '服务条款',
    'page.cookies': 'Cookie政策',

    // Common buttons
    'button.book': '立即预订',
    'button.add_to_cart': '加入购物车',
    'button.save': '保存',
    'button.cancel': '取消',
    'button.search': '搜索',
    'button.filter': '筛选',
    'button.sort': '排序',
    'button.view_more': '查看更多',
    'button.view_less': '收起',

    // Blog
    'blog.title': '旅行博客',
    'blog.subtitle': '来自世界各地的灵感、技巧和故事',
    'blog.all_posts': '所有文章',
    'blog.read_more': '阅读更多',
    'blog.homepage.title': '旅行故事与攻略',
    'blog.homepage.subtitle': '来自我们旅行专家的灵感和建议',
    'blog.homepage.read_blog': '阅读我们的博客',
    'blog.newsletter.title': '订阅我们的通讯',
    'blog.newsletter.subtitle': '获取旅行提示、目的地指南和独家优惠，直接发送到您的收件箱',
    'blog.newsletter.placeholder': '输入您的邮箱',
    'blog.newsletter.subscribe': '订阅',
    'blog.category.destination_guides': '目的地指南',
    'blog.category.travel_tips': '旅行贴士',
    'blog.category.travel_planning': '旅行规划',
    'blog.category.sustainable_travel': '可持续旅行',
    'blog.category.food_culture': '美食文化',

    // Activity details
    'activity.highlights': '亮点',
    'activity.included': '包含项目',
    'activity.excluded': '不包含项目',
    'activity.meeting_point': '集合点',
    'activity.faqs': '常见问题',
    'activity.reviews': '评价',
    'activity.similar': '类似活动',
    'activity.what_to_expect': '预期内容',
    'activity.pricing': '价格选项',
    'activity.schedule': '可用时间',
    'activity.add_ons': '附加项目',

    // Filters
    'filter.price': '价格',
    'filter.duration': '时长',
    'filter.rating': '评分',
    'filter.category': '分类',
    'filter.language': '语言',

    // Messages
    'message.no_translation': '该内容不支持所选语言',
    'message.loading': '加载中...',
    'message.not_available_in': '不支持',
    'message.not_translated': '该内容尚未翻译。请切换到英语查看此信息。',
    'message.error': '发生错误',
    'message.success': '成功！',
    'message.empty_cart': '您的购物车是空的',
    'message.empty_wishlist': '您的愿望清单是空的',

    // Homepage
    'homepage.hero.title': '找到您的完美旅行伙伴',
    'homepage.hero.subtitle': '与当地专家联系，发现真实的体验',
    'homepage.search.placeholder': '您想去哪里探索？',
    'homepage.trust.millions.title': '数百万用户信赖',
    'homepage.trust.millions.desc': '全球超过150,000个活动',
    'homepage.trust.cancellation.title': '免费取消',
    'homepage.trust.cancellation.desc': '大多数活动提供免费取消',
    'homepage.trust.guarantee.title': '最低价格保证',
    'homepage.trust.guarantee.desc': '找到更便宜的？我们退还差价',
    'homepage.destinations.title': '热门目的地',
    'homepage.destinations.subtitle': '发现世界上最令人惊叹的地方',
    'homepage.activities.title': '热门活动',
    'homepage.activities.subtitle': '我们的旅客喜爱的精选体验',
    'homepage.categories.title': '按类别探索',
    'homepage.categories.subtitle': '找到符合您兴趣的活动',
    
    // Vendor CTA Section
    'homepage.vendor.title': '成为供应商',
    'homepage.vendor.subtitle': '加入数千名活动提供商，接触全球数百万旅行者',
    'homepage.vendor.list_activity': '发布您的活动',
    'homepage.vendor.login': '供应商登录',

    // Search page
    'search.title.all_activities': '所有活动',
    'search.title.search_results': '搜索结果',
    'search.activities_found': '个活动',
    'search.placeholder': '搜索活动...',
    'search.sort.recommended': '推荐',
    'search.sort.price_low_high': '价格：由低到高',
    'search.sort.price_high_low': '价格：由高到低',
    'search.sort.highest_rated': '评分最高',
    'search.sort.duration': '时长',
    'search.load_more': '加载更多',
    'search.loading': '加载中...',
    'search.no_results.title': '未找到活动',
    'search.no_results.subtitle': '请尝试调整筛选条件或搜索词',
    'search.clear_filters': '清除筛选',

    // Filter sidebar
    'filter.title': '筛选',
    'filter.clear_all': '清除全部',
    'filter.all_categories': '所有分类',
    'filter.all_destinations': '所有目的地',
    'filter.price_range': '价格范围 (€)',
    'filter.price.min': '最低',
    'filter.price.max': '最高',
    'filter.duration_hours': '时长（小时）',
    'filter.min_rating': '最低评分',
    'filter.any_rating': '任意评分',
    'filter.features': '特色',
    'filter.free_cancellation': '免费取消',
    'filter.instant_confirmation': '即时确认',
    'filter.skip_the_line': '免排队',
    'filter.bestseller': '热销',

    // Activity badges
    'badge.bestseller': '畅销',
    'badge.skip_the_line': '免排队',
    'badge.free_cancellation': '免费取消',
    'badge.instant_confirmation': '即时确认',

    // Activity detail sections
    'activity.overview': '概览',
    'activity.important_info': '重要信息',
    'activity.what_to_bring': '需要携带',
    'activity.not_suitable_for': '不适合',
    'activity.dress_code': '着装要求',
    'activity.covid_measures': 'COVID-19安全措施',
    'activity.provider': '活动供应商',
    'activity.verified': '已验证',
    'activity.meeting_point_photos': '集合点照片',
    'activity.map_not_available': '地图不可用',
    'activity.booked': '已预订',

    // Booking widget
    'booking.select_date': '选择日期',
    'booking.select_time': '选择时间',
    'booking.select_tickets': '选择门票',
    'booking.adult': '成人',
    'booking.child': '儿童',
    'booking.total': '总计',
    'booking.from': '起价',
    'booking.per_person': '每人',
    'booking.popular_choice': '热门选择',
    'booking.people_viewing': '人',
    'booking.viewing_now': '正在浏览此活动',
    'booking.only_spots_left': '仅剩',
    'booking.spots_left': '个位置',
    'booking.for_selected_date': '在选定日期！',
    'booking.duration': '时长',
    'booking.max_group_size': '最大团体人数',
    'booking.max_people': '最多',
    'booking.people': '人',
    'booking.add_to_cart': '加入购物车',
    'booking.adding': '正在添加...',
    'booking.free_cancellation': '免费取消至',
    'booking.hours_before': '小时前',
    'booking.instant_confirmation': '即时确认',
    'booking.was': '原价',
    
    // Time slots
    'timeslots.select_time': '选择时间',
    'timeslots.sold_out': '售罄',
    
    // Add-ons
    'addons.add_ons': '附加项目与额外服务',
    'addons.optional': '可选',
    'addons.extra': '额外',
    'addons.required': '必需',
    'addons.optional_extras': '可选额外项目',
    'addons.total': '总计',
    
    // Pricing tiers
    'pricing.select_option': '选择选项',
    
    // Reviews
    'reviews.customer_reviews': '用户评价',
    'reviews.write_review': '写评价',
    'reviews.helpful': '有用',
    'reviews.show_more': '显示更多',
    'reviews.show_less': '收起',
    
    // Destinations
    'destination.tokyo': '东京',
    'destination.paris': '巴黎',
    'destination.london': '伦敦',
    'destination.new-york': '纽约',
    'destination.rome': '罗马',
    'destination.barcelona': '巴塞罗那',
    'destination.berlin': '柏林',
    'destination.amsterdam': '阿姆斯特丹',
    'destination.prague': '布拉格',
    
    // Activity Features
    'features.title': '活动特色',
    'features.verified_activity': '认证活动',
    'features.best_price_guarantee': '最低价格保证',
    'features.mobile_ticket': '手机票券',
    'features.likely_to_sell_out': '可能售罄',
    'features.response_time': '响应时间',
    'features.wheelchair_accessible': '轮椅无障碍',
    'features.stroller_accessible': '婴儿车友好',
    'features.service_animals_allowed': '允许服务性动物',
    'features.infant_seats_available': '提供婴儿座椅',
    'features.gift_option_available': '礼品选项可用',
    'features.reserve_now_pay_later': '现在预订，稍后付款',
    'features.covid_measures': 'COVID-19安全措施',
    'features.weather_dependent': '依赖天气条件',
    'features.video_preview_available': '提供视频预览',
    
    // Categories
    'category.food-drink': '美食餐饮',
    'category.tours-sightseeing': '观光游览',
    'category.outdoor-adventures': '户外探险',
    'category.arts-culture': '艺术文化',
    'category.nightlife-entertainment': '夜生活娱乐',
    'category.workshops-classes': '工作坊课程',
    'category.family-friendly': '亲子友好',
    'category.romantic': '浪漫',
    'category.wellness-spa': '健康水疗',
    'category.sports-fitness': '运动健身',
    'category.museums-attractions': '博物馆景点',
    
    // Pricing Tiers
    'pricing.standard': '标准',
    'pricing.premium': '高级',
    'pricing.vip': '贵宾',
    'pricing.pedestal_access': '基座参观',
    'pricing.crown_access': '皇冠参观',
    'pricing.mezzanine': '中层座位',
    'pricing.orchestra': '乐池座位',
    'pricing.vip_package': '贵宾套餐',
    'pricing.at_the_top': '顶层观景',
    'pricing.at_the_top_sky': '天空观景',
    
    // Countries
    'country.france': '法国',
    'country.united_kingdom': '英国',
    'country.italy': '意大利',
    'country.spain': '西班牙',
    'country.netherlands': '荷兰',
    'country.united_states': '美国',
    'country.japan': '日本',
    'country.united_arab_emirates': '阿拉伯联合酋长国',
    'country.czech_republic': '捷克共和国',
    'country.turkey': '土耳其',
    
    // Language names
    'language.english': '英语',
    'language.french': '法语',
    'language.spanish': '西班牙语',
    'language.italian': '意大利语',
    'language.german': '德语',
    'language.portuguese': '葡萄牙语',
    'language.chinese': '中文',
    'language.japanese': '日语',
    
    // About page
    'about.title': '关于我们',
    'about.hero_subtitle': '连接旅行者与全球难忘体验',
    'about.mission_title': '我们的使命',
    'about.mission_p1': '在FindTravelMate，我们相信旅行不仅仅是参观新地方——它是关于建立有意义的联系，发现真实的体验，创造一生的回忆。',
    'about.mission_p2': '我们与全球的当地专家和活动提供商合作，为您带来最好的游览、活动和体验。无论您寻求冒险、文化、放松还是完全独特的东西，我们都在这里帮助您找到完美的旅行伙伴。',
    'about.value_community': '社区',
    'about.value_community_desc': '在旅行者和当地专家之间建立联系',
    'about.value_global': '全球覆盖',
    'about.value_global_desc': '全球目的地超过150,000个活动',
    'about.value_quality': '质量',
    'about.value_quality_desc': '仅提供经过验证的供应商和真实体验',
    'about.value_passion': '热情',
    'about.value_passion_desc': '由对旅行和发现的热爱驱动',
    'about.story_title': '我们的故事',
    'about.story_p1': 'FindTravelMate成立于2020年，源于一个简单的想法：每个旅行者都应该与真实的当地体验建立联系。我们的创始人本身就是充满激情的旅行者，他们看到了游客与真正了解目的地的优秀人士之间的差距。',
    'about.story_p2': '今天，我们已经发展成为一个全球平台，连接数百万旅行者与数千个经过验证的供应商，覆盖数百个目的地。但我们的使命保持不变——让每次旅程都变得非凡。',
    'about.stat_activities': '活动',
    'about.stat_destinations': '目的地',
    'about.stat_travelers': '快乐旅行者',
    'about.stat_vendors': '认证供应商',
    'about.cta_title': '准备开始您的旅程了吗？',
    'about.cta_subtitle': '探索等待您的数千个令人惊叹的体验',
    'about.cta_button': '探索活动',

    // Careers page
    'careers.title': '加入我们的团队',
    'careers.hero_subtitle': '帮助我们连接数百万旅行者与难忘体验',
    'careers.why_work_title': '为什么选择我们',
    'careers.passion_travel': '对旅行的热情',
    'careers.passion_travel_desc': '与和您一样热爱旅行的人一起工作',
    'careers.collaborative_culture': '协作文化',
    'careers.collaborative_culture_desc': '加入一个多元化、包容性的团队，重视每个声音',
    'careers.growth_opportunities': '成长机会',
    'careers.growth_opportunities_desc': '持续学习和职业发展',
    'careers.benefits_title': '福利待遇',
    'careers.benefit_salary': '具有竞争力的薪资和股权包',
    'careers.benefit_insurance': '全面的健康、牙科和视力保险',
    'careers.benefit_flexible': '灵活的工作时间和远程工作选择',
    'careers.benefit_pto': '无限假期政策',
    'careers.benefit_travel': '年度旅行津贴用于体验',
    'careers.benefit_development': '专业发展预算',
    'careers.benefit_401k': '401(k)匹配',
    'careers.benefit_parental': '育儿假',
    'careers.open_positions': '职位空缺',
    'careers.no_openings': '目前没有职位空缺。请稍后查看！',
    'careers.apply_now': '立即申请',
    'careers.cta_title': '没有看到合适的职位？',
    'careers.cta_subtitle': '我们一直在寻找有才华的人。请发送您的简历！',
    'careers.get_in_touch': '联系我们',
    'careers.job_engineering': '工程',
    'careers.job_product': '产品',
    'careers.job_customer_success': '客户成功',
    'careers.job_marketing': '市场营销',
    'careers.job_remote': '远程',
    'careers.job_fulltime': '全职',
    'careers.job_senior_fullstack': '高级全栈工程师',
    'careers.job_product_manager': '产品经理',
    'careers.job_customer_success_manager': '客户成功经理',
    'careers.job_marketing_manager': '市场营销经理',

    // User Account Pages
    // Profile/My Account page
    'account.my_account': '我的账户',
    'account.profile': '个人资料',
    'account.my_bookings': '我的预订',
    'account.wishlist': '愿望清单',
    'account.settings': '设置',
    'account.profile_information': '个人资料信息',
    'account.edit_profile': '编辑个人资料',
    'account.full_name': '全名',
    'account.phone_number': '电话号码',
    'account.email_address': '电子邮件地址',
    'account.verified': '已验证',
    'account.not_verified': '未验证',
    'account.not_set': '未设置',
    'account.member_since': '会员自',
    'account.save_changes': '保存更改',
    'account.cancel': '取消',
    'account.loading': '加载中...',
    'account.total_bookings': '总预订数',
    'account.wishlist_items': '愿望清单项目',
    'account.reviews': '评价',

    // My Bookings page
    'bookings.title': '我的预订',
    'bookings.booking_confirmed': '预订已确认！',
    'bookings.confirmation_email_sent': '您的预订已确认。确认邮件已发送至您的邮箱地址。',
    'bookings.book_more_activities': '预订更多活动',
    'bookings.return_to_homepage': '返回首页',
    'bookings.confirmation_success': '您的预订已确认！请查看您的邮箱获取确认详情。',
    'bookings.no_bookings_yet': '暂无预订',
    'bookings.start_exploring': '开始探索并预订您的下一次冒险',
    'bookings.browse_activities': '浏览活动',
    'bookings.booking_reference': '预订参考号',
    'bookings.status_confirmed': '已确认',
    'bookings.status_pending': '待处理',
    'bookings.status_cancelled': '已取消',
    'bookings.status_completed': '已完成',
    'bookings.adult': '成人',
    'bookings.adults': '成人',
    'bookings.child': '儿童',
    'bookings.children': '儿童',
    'bookings.duration': '时长',
    'bookings.special_requirements': '特殊要求',
    'bookings.view_details': '查看详情',
    'bookings.cancel_booking': '取消预订',
    'bookings.leave_review': '留下评价',
    'bookings.loading_bookings': '正在加载您的预订...',

    // Wishlist page
    'wishlist.title': '我的愿望清单',
    'wishlist.activity': '个活动',
    'wishlist.activities': '个活动',
    'wishlist.saved': '已保存',
    'wishlist.empty_title': '您的愿望清单是空的',
    'wishlist.empty_description': '通过点击心形图标开始添加您感兴趣的活动',
    'wishlist.explore_activities': '探索活动',
    'wishlist.loading': '正在加载您的愿望清单...',
    'wishlist.try_again': '重试',
    'wishlist.failed_to_load': '加载愿望清单失败。请重试。',

    // Vendor Dashboard
    'vendor.dashboard': '供应商面板',
    'vendor.welcome_back': '欢迎回来',
    'vendor.add_activity': '添加活动',
    'vendor.total_activities': '总活动数',
    'vendor.active_activities': '活跃活动',
    'vendor.total_bookings': '总预订数',
    'vendor.total_revenue': '总收入',
    'vendor.your_activities': '您的活动',
    'vendor.no_activities_yet': '暂无活动',
    'vendor.get_started_message': '开始创建您的第一个活动。与全世界的旅行者分享您的体验！',
    'vendor.create_first_activity': '创建您的第一个活动',
    'vendor.activity': '活动',
    'vendor.category': '分类',
    'vendor.price': '价格',
    'vendor.rating': '评分',
    'vendor.status': '状态',
    'vendor.actions': '操作',
    'vendor.active': '活跃',
    'vendor.inactive': '不活跃',
    'vendor.view': '查看',
    'vendor.edit': '编辑',
    'vendor.delete': '删除',
    'vendor.activate': '激活',
    'vendor.deactivate': '停用',
    'vendor.recent_bookings': '最近预订',
    'vendor.list': '列表',
    'vendor.calendar': '日历',
    'vendor.no_bookings_yet': '暂无预订。',
    'vendor.booking_ref': '预订参考',
    'vendor.customer': '客户',
    'vendor.date': '日期',
    'vendor.amount': '金额',
    'vendor.approve': '批准',
    'vendor.reject': '拒绝',
    'vendor.check_in': '签到',
    'vendor.cancel': '取消',
    'vendor.loading': '加载中...',
    'vendor.confirm_delete': '您确定要删除此活动吗？',
    'vendor.delete_failed': '删除活动失败',
    'vendor.toggle_failed': '切换活动状态失败',
    'vendor.approve_confirm': '批准此预订？',
    'vendor.approve_failed': '批准预订失败',
    'vendor.reject_reason': '请提供拒绝的原因：',
    'vendor.reject_failed': '拒绝预订失败',
    'vendor.cancel_reason': '请提供取消的原因：',
    'vendor.cancel_failed': '取消预订失败',
    'vendor.checkin_confirm': '将此预订标记为已签到？',
    'vendor.checkin_failed': '签到预订失败',

    // Vendor Login
    'vendor.login_title': '供应商登录',
    'vendor.login_subtitle': '登录以管理您的活动',
    'vendor.email_address': '电子邮件地址',
    'vendor.password': '密码',
    'vendor.signing_in': '登录中...',
    'vendor.sign_in': '登录',
    'vendor.no_account': '没有供应商账户？',
    'vendor.register_here': '在此注册',
    'vendor.back_to_home': '返回首页',
    'vendor.access_denied': '访问被拒绝。需要供应商账户。',
    'vendor.verify_failed': '验证供应商账户失败。请重试。',
    'vendor.invalid_credentials': '电子邮件或密码无效',

    // Cart page
    'cart.empty': '您的购物车是空的',
    'cart.browse_activities': '浏览活动',
    'cart.title': '购物车',
    'cart.order_summary': '订单摘要',
    'cart.proceed_to_checkout': '前往结账',
    'cart.continue_shopping': '继续购物',
    'cart.secure_checkout': '安全结账',

    // Checkout page
    'checkout.back_to_cart': '返回购物车',
    'checkout.title': '结账',
    'checkout.first_name': '名 *',
    'checkout.last_name': '姓 *',
    'checkout.email': '电子邮件地址 *',
    'checkout.phone': '电话号码 *',
    'checkout.payment_method': '支付方式',
    'checkout.order_summary': '订单摘要',
    'checkout.validate_name': '请输入您的全名',
    'checkout.validate_email': '请输入您的电子邮件地址',
    'checkout.validate_phone': '请输入您的电话号码',
    'checkout.validate_terms': '请同意条款和条件',
    'checkout.booking_success': '预订成功完成！',
    'checkout.booking_error': '预订失败。请重试。',

    // Header dashboard links
    'nav.admin_dashboard': '管理员面板',
    'nav.vendor_dashboard': '供应商面板',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.activities': 'Activités',
    'nav.destinations': 'Destinations',
    'nav.blog': 'Blog',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.signin': 'Se connecter',
    'nav.signup': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    'nav.profile': 'Profil',
    'nav.wishlist': 'Liste de souhaits',
    'nav.cart': 'Panier',
    'nav.bookings': 'Mes réservations',
    
    // Footer sections
    'footer.company': 'Entreprise',
    'footer.support': 'Support', 
    'footer.vendors': 'Pour les Partenaires',
    
    // Company pages
    'page.about_us': 'À propos de nous',
    'page.careers': 'Carrières',
    'page.press': 'Presse',
    'page.blog': 'Blog',
    
    // Support pages
    'page.help_center': 'Centre d\'aide',
    'page.contact_us': 'Nous contacter',
    'page.cancellation_policy': 'Politique d\'annulation',
    'page.privacy_policy': 'Politique de confidentialité',
    
    // Vendor pages
    'page.list_experience': 'Répertoriez votre expérience',
    'page.vendor_login': 'Connexion partenaire',
    'page.vendor_dashboard': 'Tableau de bord partenaire',
    'page.affiliate_program': 'Programme d\'affiliation',
    
    // Footer additional
    'footer.connect': 'Se connecter',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter_desc': 'Recevez des conseils de voyage et de l\'inspiration dans votre boîte de réception.',
    'footer.subscribe': 'S\'abonner',
    'footer.your_email': 'Votre email',
    'footer.copyright': '© 2024 FindTravelMate. Tous droits réservés.',
    'page.terms': 'Conditions d\'utilisation',
    'page.cookies': 'Politique des cookies',

    // Common buttons
    'button.book': 'Réserver maintenant',
    'button.add_to_cart': 'Ajouter au panier',
    'button.save': 'Enregistrer',
    'button.cancel': 'Annuler',
    'button.search': 'Rechercher',
    'button.filter': 'Filtrer',
    'button.sort': 'Trier',
    'button.view_more': 'Voir plus',
    'button.view_less': 'Voir moins',

    // Blog
    'blog.title': 'Blog de Voyage',
    'blog.subtitle': 'Inspiration, conseils et histoires du monde entier',
    'blog.all_posts': 'Tous les Articles',
    'blog.read_more': 'Lire Plus',
    'blog.homepage.title': 'Histoires et Conseils de Voyage',
    'blog.homepage.subtitle': 'Inspiration et conseils de nos experts en voyage',
    'blog.homepage.read_blog': 'Lire Notre Blog',
    'blog.newsletter.title': 'Abonnez-vous à Notre Newsletter',
    'blog.newsletter.subtitle': 'Recevez des conseils de voyage, des guides de destinations et des offres exclusives dans votre boîte de réception',
    'blog.newsletter.placeholder': 'Entrez votre email',
    'blog.newsletter.subscribe': 'S\'abonner',
    'blog.category.destination_guides': 'Guides de Destinations',
    'blog.category.travel_tips': 'Conseils de Voyage',
    'blog.category.travel_planning': 'Planification de Voyage',
    'blog.category.sustainable_travel': 'Voyage Durable',
    'blog.category.food_culture': 'Gastronomie et Culture',

    // Activity details
    'activity.highlights': 'Points forts',
    'activity.included': 'Ce qui est inclus',
    'activity.excluded': 'Ce qui n\'est pas inclus',
    'activity.meeting_point': 'Point de rencontre',
    'activity.faqs': 'Questions fréquentes',
    'activity.reviews': 'Avis',
    'activity.similar': 'Activités similaires',
    'activity.what_to_expect': 'À quoi s\'attendre',
    'activity.pricing': 'Options de prix',
    'activity.schedule': 'Horaires disponibles',
    'activity.add_ons': 'Suppléments',

    // Filters
    'filter.price': 'Prix',
    'filter.duration': 'Durée',
    'filter.rating': 'Évaluation',
    'filter.category': 'Catégorie',
    'filter.language': 'Langue',

    // Messages
    'message.no_translation': 'Ce contenu n\'est pas disponible dans la langue sélectionnée',
    'message.loading': 'Chargement...',
    'message.not_available_in': 'non disponible en',
    'message.not_translated': 'Ce contenu n\'a pas encore été traduit. Veuillez passer à l\'anglais pour voir cette information.',
    'message.error': 'Une erreur s\'est produite',
    'message.success': 'Succès !',
    'message.empty_cart': 'Votre panier est vide',
    'message.empty_wishlist': 'Votre liste de souhaits est vide',

    // Homepage
    'homepage.hero.title': 'Trouvez Votre Partenaire de Voyage Parfait',
    'homepage.hero.subtitle': 'Connectez-vous avec des experts locaux et découvrez des expériences authentiques',
    'homepage.search.placeholder': 'Où aimeriez-vous explorer ?',
    'homepage.trust.millions.title': 'Approuvé par des millions',
    'homepage.trust.millions.desc': 'Plus de 150 000 activités dans le monde',
    'homepage.trust.cancellation.title': 'Annulation gratuite',
    'homepage.trust.cancellation.desc': 'La plupart des activités offrent une annulation gratuite',
    'homepage.trust.guarantee.title': 'Garantie du meilleur prix',
    'homepage.trust.guarantee.desc': 'Trouvé moins cher ? Nous remboursons la différence',
    'homepage.destinations.title': 'Destinations populaires',
    'homepage.destinations.subtitle': 'Découvrez les endroits les plus incroyables du monde',
    'homepage.activities.title': 'Activités les mieux notées',
    'homepage.activities.subtitle': 'Expériences sélectionnées que nos voyageurs adorent',
    'homepage.categories.title': 'Explorer par catégorie',
    'homepage.categories.subtitle': 'Trouvez des activités qui correspondent à vos intérêts',
    
    // Vendor CTA Section
    'homepage.vendor.title': 'Devenez fournisseur',
    'homepage.vendor.subtitle': 'Rejoignez des milliers de fournisseurs d\'activités et touchez des millions de voyageurs dans le monde',
    'homepage.vendor.list_activity': 'Listez votre activité',
    'homepage.vendor.login': 'Connexion fournisseur',

    // Search page
    'search.title.all_activities': 'Toutes les Activités',
    'search.title.search_results': 'Résultats de recherche pour',
    'search.activities_found': 'activités trouvées',
    'search.placeholder': 'Rechercher des activités...',
    'search.sort.recommended': 'Recommandé',
    'search.sort.price_low_high': 'Prix : Du plus bas au plus haut',
    'search.sort.price_high_low': 'Prix : Du plus haut au plus bas',
    'search.sort.highest_rated': 'Mieux noté',
    'search.sort.duration': 'Durée',
    'search.load_more': 'Charger Plus',
    'search.loading': 'Chargement...',
    'search.no_results.title': 'Aucune activité trouvée',
    'search.no_results.subtitle': 'Essayez d\'ajuster vos filtres ou termes de recherche',
    'search.clear_filters': 'Effacer les Filtres',

    // Filter sidebar
    'filter.title': 'Filtres',
    'filter.clear_all': 'Tout effacer',
    'filter.all_categories': 'Toutes les catégories',
    'filter.all_destinations': 'Toutes les destinations',
    'filter.price_range': 'Gamme de Prix (€)',
    'filter.price.min': 'Min',
    'filter.price.max': 'Max',
    'filter.duration_hours': 'Durée (heures)',
    'filter.min_rating': 'Note Minimale',
    'filter.any_rating': 'Toute note',
    'filter.features': 'Caractéristiques',
    'filter.free_cancellation': 'Annulation gratuite',
    'filter.instant_confirmation': 'Confirmation instantanée',
    'filter.skip_the_line': 'Coupe-file',
    'filter.bestseller': 'Bestseller',

    // Activity badges
    'badge.bestseller': 'BESTSELLER',
    'badge.skip_the_line': 'Coupe-file',
    'badge.free_cancellation': 'Annulation gratuite',
    'badge.instant_confirmation': 'Confirmation instantanée',

    // Activity detail sections
    'activity.overview': 'Aperçu',
    'activity.important_info': 'Informations importantes',
    'activity.what_to_bring': 'À apporter',
    'activity.not_suitable_for': 'Non adapté aux',
    'activity.dress_code': 'Code vestimentaire',
    'activity.covid_measures': 'Mesures de sécurité COVID-19',
    'activity.provider': 'Fournisseur d\'activité',
    'activity.verified': 'Vérifié',
    'activity.meeting_point_photos': 'Photos du point de rencontre',
    'activity.map_not_available': 'Carte non disponible',
    'activity.booked': 'réservé',

    // Booking widget
    'booking.select_date': 'Sélectionner la date',
    'booking.select_time': 'Sélectionner l\'heure',
    'booking.select_tickets': 'Sélectionner les billets',
    'booking.adult': 'Adulte',
    'booking.child': 'Enfant',
    'booking.total': 'Total',
    'booking.from': 'À partir de',
    'booking.per_person': 'par personne',
    'booking.popular_choice': 'CHOIX POPULAIRE',
    'booking.people_viewing': 'personnes',
    'booking.viewing_now': 'consultent cette activité maintenant',
    'booking.only_spots_left': 'Seulement',
    'booking.spots_left': 'places restantes',
    'booking.for_selected_date': 'pour la date sélectionnée !',
    'booking.duration': 'Durée',
    'booking.max_group_size': 'Taille max du groupe',
    'booking.max_people': 'Max',
    'booking.people': 'personnes',
    'booking.add_to_cart': 'Ajouter au Panier',
    'booking.adding': 'Ajout en cours...',
    'booking.free_cancellation': 'Annulation gratuite jusqu\'à',
    'booking.hours_before': 'heures avant',
    'booking.instant_confirmation': 'Confirmation instantanée',
    'booking.was': 'était',
    
    // Time slots
    'timeslots.select_time': 'Sélectionner l\'Heure',
    'timeslots.sold_out': 'Épuisé',
    
    // Add-ons
    'addons.add_ons': 'Suppléments & Extras',
    'addons.optional': 'Optionnel',
    'addons.extra': 'Extra',
    'addons.required': 'Requis',
    'addons.optional_extras': 'Extras Optionnels',
    'addons.total': 'Total',
    
    // Pricing tiers
    'pricing.select_option': 'Sélectionner une Option',
    
    // Reviews
    'reviews.customer_reviews': 'Avis Clients',
    'reviews.write_review': 'Écrire un Avis',
    'reviews.helpful': 'Utile',
    'reviews.show_more': 'Voir Plus',
    'reviews.show_less': 'Voir Moins',
    
    // Destinations
    'destination.tokyo': 'Tokyo',
    'destination.paris': 'Paris',
    'destination.london': 'Londres',
    'destination.new-york': 'New York',
    'destination.rome': 'Rome',
    'destination.barcelona': 'Barcelone',
    'destination.berlin': 'Berlin',
    'destination.amsterdam': 'Amsterdam',
    'destination.prague': 'Prague',
    
    // Activity Features
    'features.title': 'Caractéristiques de l\'Activité',
    'features.verified_activity': 'Activité Vérifiée',
    'features.best_price_guarantee': 'Garantie du Meilleur Prix',
    'features.mobile_ticket': 'Billet Mobile',
    'features.likely_to_sell_out': 'Susceptible d\'être Complet',
    'features.response_time': 'Temps de Réponse',
    'features.wheelchair_accessible': 'Accessible en Fauteuil Roulant',
    'features.stroller_accessible': 'Accessible avec Poussette',
    'features.service_animals_allowed': 'Animaux d\'Assistance Autorisés',
    'features.infant_seats_available': 'Sièges Bébé Disponibles',
    'features.gift_option_available': 'Option Cadeau Disponible',
    'features.reserve_now_pay_later': 'Réserver Maintenant, Payer Plus Tard',
    'features.covid_measures': 'Mesures de Sécurité COVID-19',
    'features.weather_dependent': 'Dépendant de la Météo',
    'features.video_preview_available': 'Aperçu Vidéo Disponible',
    
    // Categories
    'category.food-drink': 'Gastronomie et Boissons',
    'category.tours-sightseeing': 'Visites et Tourisme',
    'category.outdoor-adventures': 'Aventures en Plein Air',
    'category.arts-culture': 'Arts et Culture',
    'category.nightlife-entertainment': 'Vie Nocturne et Divertissement',
    'category.workshops-classes': 'Ateliers et Cours',
    'category.family-friendly': 'Famille',
    'category.romantic': 'Romantique',
    'category.wellness-spa': 'Bien-être et Spa',
    'category.sports-fitness': 'Sport et Fitness',
    'category.museums-attractions': 'Musées et Attractions',
    
    // Pricing Tiers
    'pricing.standard': 'Standard',
    'pricing.premium': 'Premium',
    'pricing.vip': 'VIP',
    'pricing.pedestal_access': 'Accès Piédestal',
    'pricing.crown_access': 'Accès Couronne',
    'pricing.mezzanine': 'Mezzanine',
    'pricing.orchestra': 'Orchestre',
    'pricing.vip_package': 'Forfait VIP',
    'pricing.at_the_top': 'Au Sommet',
    'pricing.at_the_top_sky': 'Au Sommet Ciel',
    
    // Countries
    'country.france': 'France',
    'country.united_kingdom': 'Royaume-Uni',
    'country.italy': 'Italie',
    'country.spain': 'Espagne',
    'country.netherlands': 'Pays-Bas',
    'country.united_states': 'États-Unis',
    'country.japan': 'Japon',
    'country.united_arab_emirates': 'Émirats arabes unis',
    'country.czech_republic': 'République tchèque',
    'country.turkey': 'Turquie',
    
    // Language names
    'language.english': 'Anglais',
    'language.french': 'Français',
    'language.spanish': 'Espagnol',
    'language.italian': 'Italien',
    'language.german': 'Allemand',
    'language.portuguese': 'Portugais',
    'language.chinese': 'Chinois',
    'language.japanese': 'Japonais',
    
    // About page
    'about.title': 'À propos de nous',
    'about.hero_subtitle': 'Connecter les voyageurs à des expériences inoubliables dans le monde entier',
    'about.mission_title': 'Notre Mission',
    'about.mission_p1': 'Chez FindTravelMate, nous croyons que voyager, c\'est plus que simplement visiter de nouveaux endroits—c\'est créer des connexions significatives, découvrir des expériences authentiques et créer des souvenirs qui durent toute une vie.',
    'about.mission_p2': 'Nous nous associons avec des experts locaux et des prestataires d\'activités du monde entier pour vous offrir les meilleurs circuits, activités et expériences. Que vous recherchiez l\'aventure, la culture, la détente ou quelque chose de complètement unique, nous sommes là pour vous aider à trouver votre partenaire de voyage parfait.',
    'about.value_community': 'Communauté',
    'about.value_community_desc': 'Créer des liens entre voyageurs et experts locaux',
    'about.value_global': 'Portée Mondiale',
    'about.value_global_desc': 'Plus de 150 000 activités dans des destinations du monde entier',
    'about.value_quality': 'Qualité',
    'about.value_quality_desc': 'Uniquement des fournisseurs vérifiés et des expériences authentiques',
    'about.value_passion': 'Passion',
    'about.value_passion_desc': 'Animés par l\'amour du voyage et de la découverte',
    'about.story_title': 'Notre Histoire',
    'about.story_p1': 'Fondée en 2020, FindTravelMate est née d\'une idée simple : chaque voyageur mérite de se connecter à des expériences locales authentiques. Nos fondateurs, eux-mêmes voyageurs passionnés, ont vu le fossé entre les touristes et les personnes incroyables qui connaissent vraiment leurs destinations.',
    'about.story_p2': 'Aujourd\'hui, nous sommes devenus une plateforme mondiale connectant des millions de voyageurs avec des milliers de fournisseurs vérifiés dans des centaines de destinations. Mais notre mission reste la même—rendre chaque voyage extraordinaire.',
    'about.stat_activities': 'Activités',
    'about.stat_destinations': 'Destinations',
    'about.stat_travelers': 'Voyageurs Heureux',
    'about.stat_vendors': 'Fournisseurs Vérifiés',
    'about.cta_title': 'Prêt à Commencer Votre Voyage ?',
    'about.cta_subtitle': 'Explorez des milliers d\'expériences incroyables qui vous attendent',
    'about.cta_button': 'Explorer les Activités',

    // Careers page
    'careers.title': 'Rejoignez Notre Équipe',
    'careers.hero_subtitle': 'Aidez-nous à connecter des millions de voyageurs avec des expériences inoubliables',
    'careers.why_work_title': 'Pourquoi Travailler Avec Nous',
    'careers.passion_travel': 'Passion pour le Voyage',
    'careers.passion_travel_desc': 'Travaillez avec des personnes qui aiment voyager autant que vous',
    'careers.collaborative_culture': 'Culture Collaborative',
    'careers.collaborative_culture_desc': 'Rejoignez une équipe diverse et inclusive qui valorise chaque voix',
    'careers.growth_opportunities': 'Opportunités de Croissance',
    'careers.growth_opportunities_desc': 'Apprentissage continu et développement de carrière',
    'careers.benefits_title': 'Avantages et Bénéfices',
    'careers.benefit_salary': 'Salaire compétitif et packages d\'actions',
    'careers.benefit_insurance': 'Assurance santé, dentaire et vision complète',
    'careers.benefit_flexible': 'Horaires flexibles et options de travail à distance',
    'careers.benefit_pto': 'Politique de congés illimités',
    'careers.benefit_travel': 'Allocation annuelle de voyage pour les expériences',
    'careers.benefit_development': 'Budget de développement professionnel',
    'careers.benefit_401k': 'Contribution équivalente au 401(k)',
    'careers.benefit_parental': 'Congé parental',
    'careers.open_positions': 'Postes Ouverts',
    'careers.no_openings': 'Aucun poste ouvert pour le moment. Revenez bientôt !',
    'careers.apply_now': 'Postuler Maintenant',
    'careers.cta_title': 'Ne Voyez Pas le Bon Poste ?',
    'careers.cta_subtitle': 'Nous recherchons toujours des personnes talentueuses. Envoyez-nous votre CV !',
    'careers.get_in_touch': 'Contactez-nous',
    'careers.job_engineering': 'Ingénierie',
    'careers.job_product': 'Produit',
    'careers.job_customer_success': 'Succès Client',
    'careers.job_marketing': 'Marketing',
    'careers.job_remote': 'À distance',
    'careers.job_fulltime': 'Temps plein',
    'careers.job_senior_fullstack': 'Ingénieur Full Stack Senior',
    'careers.job_product_manager': 'Chef de Produit',
    'careers.job_customer_success_manager': 'Responsable du Succès Client',
    'careers.job_marketing_manager': 'Responsable Marketing',

    // User Account Pages
    // Profile/My Account page
    'account.my_account': 'Mon Compte',
    'account.profile': 'Profil',
    'account.my_bookings': 'Mes Réservations',
    'account.wishlist': 'Liste de Souhaits',
    'account.settings': 'Paramètres',
    'account.profile_information': 'Informations du Profil',
    'account.edit_profile': 'Modifier le Profil',
    'account.full_name': 'Nom Complet',
    'account.phone_number': 'Numéro de Téléphone',
    'account.email_address': 'Adresse E-mail',
    'account.verified': 'Vérifié',
    'account.not_verified': 'Non vérifié',
    'account.not_set': 'Non défini',
    'account.member_since': 'Membre Depuis',
    'account.save_changes': 'Enregistrer les Modifications',
    'account.cancel': 'Annuler',
    'account.loading': 'Chargement...',
    'account.total_bookings': 'Réservations Totales',
    'account.wishlist_items': 'Éléments de la Liste de Souhaits',
    'account.reviews': 'Avis',

    // My Bookings page
    'bookings.title': 'Mes Réservations',
    'bookings.booking_confirmed': 'Réservation Confirmée !',
    'bookings.confirmation_email_sent': 'Votre réservation a été confirmée. Un email de confirmation a été envoyé à votre adresse e-mail.',
    'bookings.book_more_activities': 'Réserver Plus d\'Activités',
    'bookings.return_to_homepage': 'Retour à l\'Accueil',
    'bookings.confirmation_success': 'Votre réservation a été confirmée ! Vérifiez votre email pour les détails de confirmation.',
    'bookings.no_bookings_yet': 'Aucune réservation pour le moment',
    'bookings.start_exploring': 'Commencez à explorer et réservez votre prochaine aventure',
    'bookings.browse_activities': 'Parcourir les Activités',
    'bookings.booking_reference': 'Référence de Réservation',
    'bookings.status_confirmed': 'Confirmé',
    'bookings.status_pending': 'En Attente',
    'bookings.status_cancelled': 'Annulé',
    'bookings.status_completed': 'Terminé',
    'bookings.adult': 'adulte',
    'bookings.adults': 'adultes',
    'bookings.child': 'enfant',
    'bookings.children': 'enfants',
    'bookings.duration': 'Durée',
    'bookings.special_requirements': 'Exigences Spéciales',
    'bookings.view_details': 'Voir les Détails',
    'bookings.cancel_booking': 'Annuler la Réservation',
    'bookings.leave_review': 'Laisser un Avis',
    'bookings.loading_bookings': 'Chargement de vos réservations...',

    // Wishlist page
    'wishlist.title': 'Ma Liste de Souhaits',
    'wishlist.activity': 'activité',
    'wishlist.activities': 'activités',
    'wishlist.saved': 'sauvegardées',
    'wishlist.empty_title': 'Votre liste de souhaits est vide',
    'wishlist.empty_description': 'Commencez à ajouter des activités qui vous intéressent en cliquant sur l\'icône cœur',
    'wishlist.explore_activities': 'Explorer les Activités',
    'wishlist.loading': 'Chargement de votre liste de souhaits...',
    'wishlist.try_again': 'Réessayer',
    'wishlist.failed_to_load': 'Échec du chargement de la liste de souhaits. Veuillez réessayer.',

    // Vendor Dashboard
    'vendor.dashboard': 'Tableau de Bord Fournisseur',
    'vendor.welcome_back': 'Bon retour',
    'vendor.add_activity': 'Ajouter une Activité',
    'vendor.total_activities': 'Activités Totales',
    'vendor.active_activities': 'Activités Actives',
    'vendor.total_bookings': 'Réservations Totales',
    'vendor.total_revenue': 'Revenus Totaux',
    'vendor.your_activities': 'Vos Activités',
    'vendor.no_activities_yet': 'Aucune Activité Pour Le Moment',
    'vendor.get_started_message': 'Commencez en créant votre première activité. Partagez vos expériences avec des voyageurs du monde entier !',
    'vendor.create_first_activity': 'Créer Votre Première Activité',
    'vendor.activity': 'Activité',
    'vendor.category': 'Catégorie',
    'vendor.price': 'Prix',
    'vendor.rating': 'Évaluation',
    'vendor.status': 'Statut',
    'vendor.actions': 'Actions',
    'vendor.active': 'Active',
    'vendor.inactive': 'Inactive',
    'vendor.view': 'Voir',
    'vendor.edit': 'Modifier',
    'vendor.delete': 'Supprimer',
    'vendor.activate': 'Activer',
    'vendor.deactivate': 'Désactiver',
    'vendor.recent_bookings': 'Réservations Récentes',
    'vendor.list': 'Liste',
    'vendor.calendar': 'Calendrier',
    'vendor.no_bookings_yet': 'Aucune réservation pour le moment.',
    'vendor.booking_ref': 'Réf. Réservation',
    'vendor.customer': 'Client',
    'vendor.date': 'Date',
    'vendor.amount': 'Montant',
    'vendor.approve': 'Approuver',
    'vendor.reject': 'Rejeter',
    'vendor.check_in': 'Enregistrer',
    'vendor.cancel': 'Annuler',
    'vendor.loading': 'Chargement...',
    'vendor.confirm_delete': 'Êtes-vous sûr de vouloir supprimer cette activité ?',
    'vendor.delete_failed': 'Échec de la suppression de l\'activité',
    'vendor.toggle_failed': 'Échec du changement de statut de l\'activité',
    'vendor.approve_confirm': 'Approuver cette réservation ?',
    'vendor.approve_failed': 'Échec de l\'approbation de la réservation',
    'vendor.reject_reason': 'Veuillez fournir une raison pour le rejet :',
    'vendor.reject_failed': 'Échec du rejet de la réservation',
    'vendor.cancel_reason': 'Veuillez fournir une raison pour l\'annulation :',
    'vendor.cancel_failed': 'Échec de l\'annulation de la réservation',
    'vendor.checkin_confirm': 'Marquer cette réservation comme enregistrée ?',
    'vendor.checkin_failed': 'Échec de l\'enregistrement de la réservation',

    // Vendor Login
    'vendor.login_title': 'Connexion Fournisseur',
    'vendor.login_subtitle': 'Connectez-vous pour gérer vos activités',
    'vendor.email_address': 'Adresse E-mail',
    'vendor.password': 'Mot de Passe',
    'vendor.signing_in': 'Connexion en cours...',
    'vendor.sign_in': 'Se Connecter',
    'vendor.no_account': 'Pas de compte fournisseur ?',
    'vendor.register_here': 'Inscrivez-vous ici',
    'vendor.back_to_home': 'Retour à l\'Accueil',
    'vendor.access_denied': 'Accès refusé. Compte fournisseur requis.',
    'vendor.verify_failed': 'Échec de la vérification du compte fournisseur. Veuillez réessayer.',
    'vendor.invalid_credentials': 'Email ou mot de passe invalide',

    // Cart page
    'cart.empty': 'Votre panier est vide',
    'cart.browse_activities': 'Parcourir les Activités',
    'cart.title': 'Panier',
    'cart.order_summary': 'Récapitulatif de la Commande',
    'cart.proceed_to_checkout': 'Passer à la Caisse',
    'cart.continue_shopping': 'Continuer vos Achats',
    'cart.secure_checkout': 'Paiement Sécurisé',

    // Checkout page
    'checkout.back_to_cart': 'Retour au Panier',
    'checkout.title': 'Paiement',
    'checkout.first_name': 'Prénom *',
    'checkout.last_name': 'Nom *',
    'checkout.email': 'Adresse Email *',
    'checkout.phone': 'Numéro de Téléphone *',
    'checkout.payment_method': 'Mode de Paiement',
    'checkout.order_summary': 'Récapitulatif de la Commande',
    'checkout.validate_name': 'Veuillez entrer votre nom complet',
    'checkout.validate_email': 'Veuillez entrer votre adresse email',
    'checkout.validate_phone': 'Veuillez entrer votre numéro de téléphone',
    'checkout.validate_terms': 'Veuillez accepter les conditions générales',
    'checkout.booking_success': 'Réservation effectuée avec succès !',
    'checkout.booking_error': 'Échec de la réservation. Veuillez réessayer.',

    // Header dashboard links
    'nav.admin_dashboard': 'Tableau de Bord Admin',
    'nav.vendor_dashboard': 'Tableau de Bord Partenaire',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language
    if (savedLanguage && languages.some(l => l.code === savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    localStorage.setItem('preferredLanguage', newLanguage)
  }

  const getTranslation = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key
  }

  const getDestinationName = (destinationSlug: string, fallbackName: string): string => {
    const translationKey = `destination.${destinationSlug}`
    const translated = translations[language][translationKey] || translations['en'][translationKey]
    return translated || fallbackName
  }

  const getCategoryName = (categorySlug: string, fallbackName: string): string => {
    const translationKey = `category.${categorySlug}`
    const translated = translations[language][translationKey] || translations['en'][translationKey]
    return translated || fallbackName
  }

  const getPricingTierName = (tierName: string): string => {
    // Convert tier name to key format (lowercase, spaces to underscores)
    const key = tierName.toLowerCase().replace(/\s+/g, '_')
    const translationKey = `pricing.${key}`
    const translated = translations[language][translationKey] || translations['en'][translationKey]
    return translated || tierName // Fallback to original name if no translation
  }

  const getCountryName = (countryName: string): string => {
    // Convert country name to key format (lowercase, spaces to underscores)
    const key = countryName.toLowerCase().replace(/\s+/g, '_')
    const translationKey = `country.${key}`
    const translated = translations[language][translationKey] || translations['en'][translationKey]
    return translated || countryName // Fallback to original name if no translation
  }

  const getLanguageName = (languageName: string): string => {
    // Convert language name to key format (lowercase, spaces to underscores)
    const key = languageName.toLowerCase().replace(/\s+/g, '_')
    const translationKey = `language.${key}`
    const translated = translations[language][translationKey] || translations['en'][translationKey]
    return translated || languageName // Fallback to original name if no translation
  }


  const value = {
    language,
    setLanguage,
    getTranslation,
    getDestinationName,
    getCategoryName,
    getPricingTierName,
    getCountryName,
    getLanguageName,
    languageOptions: languages,
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}